# File: docker-compose.yml (Container Orchestration)

version: '3.8'

services:
  backend:
    build: ./
    ports:
      - "5000:5000"
    environment:
      - OPENAI_API_KEY=your-api-key-here
  
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend